name: Build
# This workflow is triggered for every pull request and push to master
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - $default-branch

jobs:
  install:
    name: NPM install
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # Set the node version
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # Restore the cache if there are any, so we can run the install faster
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Install
      - run: npm install
  lint:
    name: Run lint
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Lint
      - run: npm run lint
  test:
    name: Run tests
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Runs all tests
      - run: npm run test
  build:
    name: Run prod build
    needs: install
    runs-on: ubuntu-latest
    steps:
      # Run the build as well, to make sure it does build
      - run: npm run build
