name: Build
# This workflow is triggered for every pull request and push to master
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - master
    ignore-tags:
      # Do not run on any tags, because the publish workflow will handle this
      - '**'

jobs:
  build:
    name: Lint, Run Test, Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2
      # Set the node version
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      # Restore the cache if there are any, so we can run the install faster
      - uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      # Install
      - run: yarn install
      # Lint
      - run: yarn lint
      # Runs all tests
      - run: yarn test
      # Run the build as well, to make sure it does build
      - run: yarn build
